CREATE TABLE IF NOT EXISTS `poc`.`cpe_table` (
  `CPE_IP_ADDRESS` VARCHAR(50) NOT NULL,
  `CPE_USERNAME` VARCHAR(100) NOT NULL,
  `CPE_PASSWORD` VARCHAR(100) NOT NULL,
  `MODEL_NUMBER` VARCHAR(50) NULL,
  `SERIAL_NUMBER` VARCHAR(50) NULL,
  `MAC_ADDRESS` VARCHAR(50) NULL,
  `FIRMWARE` VARCHAR(50) NULL,
  `OUTBOUND_IP` VARCHAR(50) NULL,
  `LISTENING_PORT` VARCHAR(50) NULL,
  `ACS_URL` VARCHAR(50) NULL,
  `CWMP_USER_NAME` VARCHAR(50) NULL,
  `CWMP_PASSWORD` VARCHAR(50) NULL,
  `CWMP_ANNEX` VARCHAR(50) NULL,
  `CWMP_PERIODIC_INFO` VARCHAR(50) NULL,
  PRIMARY KEY (`CPE_IP_ADDRESS`));

CREATE TABLE IF NOT EXISTS `poc`.`post_cpe_table` (
  `CPE_IP_ADDRESS` VARCHAR(50) NOT NULL,
  `CPE_USERNAME` VARCHAR(100) NOT NULL,
  `CPE_PASSWORD` VARCHAR(100) NOT NULL,
  `MODEL_NUMBER` VARCHAR(50) NULL,
  `SERIAL_NUMBER` VARCHAR(50) NULL,
  `MAC_ADDRESS` VARCHAR(50) NULL,
  `FIRMWARE` VARCHAR(50) NULL,
  `OUTBOUND_IP` VARCHAR(50) NULL,
  `LISTENING_PORT` VARCHAR(50) NULL,
  `ACS_URL` VARCHAR(50) NULL,
  `CWMP_USER_NAME` VARCHAR(50) NULL,
  `CWMP_PASSWORD` VARCHAR(50) NULL,
  `CWMP_ANNEX` VARCHAR(50) NULL,
  `CWMP_PERIODIC_INFO` VARCHAR(50) NULL,
  PRIMARY KEY (`CPE_IP_ADDRESS`),
  FOREIGN KEY (CPE_IP_ADDRESS) REFERENCES cpe_table(CPE_IP_ADDRESS));


CREATE TABLE IF NOT EXISTS `poc`.`phone_lines` (
  `PHONE_LINES_ID` INT AUTO_INCREMENT NOT NULL,
  `CPE_IP_ADDRESS` VARCHAR(50) NOT NULL,
  `USER_NAME` VARCHAR(50) NULL,
  `PASSWORD` VARCHAR(50) NULL,
  `REGISTRATION_STATUS` VARCHAR(50) NULL,
  `PRE_MIGRATION_STATUS` VARCHAR(50) NULL,
  `MIGRATION_STATUS` VARCHAR(50) NULL,
  `STATUS_UPDATE_TIME` DATETIME NULL,
  PRIMARY KEY (`PHONE_LINES_ID`),
  FOREIGN KEY (CPE_IP_ADDRESS) REFERENCES cpe_table(CPE_IP_ADDRESS));
  
